### PR TITLE
Feat: navbar branch

### PR DESCRIPTION
**Pull request by VictorMugisha**
#### What does this PR do?

- Implements a navbar feature component

#### Description of the component?

- The component is fully responsive from mobile throughout the desktop version

#### How should this be manually tested?

- Clone the repo

- checkout to branch `ft/navbar`

- Run `npm run dev` to start the tailwind 

- Open the `index.html` in Live Server

#### What are the relevant Trello stories?

- Link to my implemented [Trello](https://trello.com/c/civQzcr5/7-navbar-component) story 

#### Screenshots (if appropriate)

image

### CODE REVIEW

**Review by kelliaUmuhire — COMMENTED** [review]
Besides the top padding that differs from the design's, everything else looks amazing!

**Review by MikeManzi — APPROVED** [review]
LGTM!

**Review by tuyishimehono — APPROVED** [review]
Great work. Everything looks good so far and I like the way you used DOM and BOM to deal with the menu items.

**Review by Kamikazi-Deborah — COMMENTED** [review]
Good job

**Pull request merged**
