### PR TITLE
feat: References Section

### PR DESCRIPTION
**Pull request by VictorMugisha**
#### What does this PR do?

- Implements the references section

#### What are the relevant Trello stories?
Here is the [Trello link](https://trello.com/c/b9IFL3qH/10-the-section-with-a-yellow-backgroundreferences)

#### Screenshot
image

### CODE REVIEW

**Review by Kamikazi-Deborah — APPROVED** [review]

**Review by tpambrose — APPROVED** [review]
Looks good to me

**Review by MikeManzi — COMMENTED** [review]
LGTM! But make sure you fix the conflicts in the index file

**Review by kelliaUmuhire — APPROVED** [review]
Looks good!

**Comment by tuyishimehono** [comment]
We resolved the conflicts in index.html

**Pull request merged**
