### PR TITLE
Feat: Hero section

### PR DESCRIPTION
**Pull request by MikeManzi**
#### What does this PR do?

-   Implementation of the hero section

#### Description of Task to be completed?

- User can be able to see the hero section

#### How should this be manually tested?

- Clone the repo

- checkout to branch `ft/hero-section`

- Run `npm install` to install modules

- Run `npm run dev` to start the development server

#### What are the relevant Pivotal Tracker/trello stories?

- Link to implemented [Trello](https://trello.com/c/XODC7Fjz/9-hero-section) story

#### Screenshots 

image

WhatsApp Image 2024-05-30 at 11 40 04_a9b65a69

### CODE REVIEW

**Review by VictorMugisha — COMMENTED** [review]
ILGTM!

**Review by kelliaUmuhire — APPROVED** [review]
This looks amazing!

**Review by Kamikazi-Deborah — APPROVED** [review]

**Review by VictorMugisha — COMMENTED** [review]
It looks good!

**Review by tpambrose — APPROVED** [review]
everything looks good .👌

**Pull request merged**
