### PR TITLE
feat: added footer component

### PR DESCRIPTION
**Pull request by Deborah-Kamikazi**
#### What does this PR do?

-   Implementation of the footer

#### Description of Task to be completed?

- User can be able to see the footer

#### How should this be manually tested?

- Clone the repo

- checkout to branche `ft/footer`

- Run `npm install` to install modules

- Run `npm run dev` to start the development server

#### What are the relevant Pivotal Tracker/trello stories?

- link to my implemented [Trello](https://trello.com/c/bySLNzSw/11-footer-component) story

#### Screenshots 

image

### CODE REVIEW

**Review by tpambrose — APPROVED** [review]
looks okay

**Review by tuyishimehono — APPROVED** [review]
Amazing work. Everything looks good so far!

**Review by MikeManzi — CHANGES_REQUESTED** [review]
Amazing work so far. But the red shape's size needs to be adjusted, it looks bigger than it is on the design.
image

**Review by tpambrose — COMMENTED** [review]
okay

**Pull request merged**
